### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by P1tch0o** [ali-ann/drupal-forum-access#1]
After installing the [drupal-forum-access](https://github.com/ali-ann/drupal-forum-access) project and performing some tests I encountered the following problems:

- There is an error while trying to create other types of content besides topic. If there are already other types of content created before the module installation, an error occurs when trying to make **Rebuild permissions**.
- I use the “Content Moderation” module to control the posting status of the topics, however the users of a forum can view the unpublished topics of the other users of the same forum and the users do not even have the **View own unpublished content** or **Administer content** permission.

**Comment by ali-ann** [comment]
@P1tch0o Thanks a lot for your feebdback and detailed description. I will try to test and fix it asap.

**Comment by ali-ann** [comment]
@P1tch0o I made some fixes. Could you check if it help to resolve issues that you've described above? Please, **Rebuild permissions** before checking.

**Comment by P1tch0o** [comment]
The error in trying to create other content types has been solved, however the users of a forum can still view the unpublished topics of other users of the same forum.
Unpublished topics do not appear in the forum, however you can access the topic with the node url.

Observations:
In the tests I did not use the Content Moderation module to avoid influencing the results.
Now with the EDIT POSTS and DELETE POSTS permissions, from ACCESS CONTROL, users can only edit and delete the published topics as expected.

**Comment by ali-ann** [comment]
@P1tch0o Thanks a lot for your fix. I look at it and it looks fine for me and I merged it with the main repository. I close this issue as fixed.

**Comment by P1tch0o** [comment]
During the tests I discovered that I did not fix the unpublished topics problem.

Moderators are getting **Access denied** when trying to access an unpublished topic if I do not manually _rebuild permissions_ after the creation of the topic.
But after I rebuild permissions, normal users can view unpublished topics of the other users of the same forum.

I will do a fresh installation to confirm this.

**Comment by P1tch0o** [comment]
I am doing some tests because somehow users can view unpublished topics from other users again. I do not know how they have access to view unpublished content once the function **forum_access_node_access** is returning **AccessResult::neutral();**
